In [6]:
#importing dependencies #span mail project
import numpy as np
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


path= r'E:\PythonPracticenew\datasets\mail_data.csv'
df = pd.read_csv(path)

In [20]:
#checking whether there are null values and changing null values with null strings
df.where((pd.notnull(df)),'')

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [21]:
#printing the first 5 rows of the dataset
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [22]:
#checking the number of rows and columns in the dataframe
df.shape

(5572, 2)

In [37]:
#replace the text value in Categorical Variable
df.replace({'Category':{'ham':1,'spam':0}},inplace=True)
df.head()

   Category                                            Message
0         1  Go until jurong point, crazy.. Available only ...
1         1                      Ok lar... Joking wif u oni...
2         0  Free entry in 2 a wkly comp to win FA Cup fina...
3         1  U dun say so early hor... U c already then say...
4         1  Nah I don't think he goes to usf, he lives aro...

In [43]:
#seperating target and feature variables
X = df['Message']
Y = df['Category']

In [ ]:
#splitting the data in train and test split 
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,train_size=0.2,stratify=Y,random_state=3)

2076    Must come later.. I normally bathe him in da a...
1005                           Umma. Did she say anything
329                      Cool, text me when you're parked
621                 Dear we got  &lt;#&gt;  dollars hi hi
1320                       Correct. So how was work today
                              ...
3305    IM GONNAMISSU SO MUCH!!I WOULD SAY IL SEND U A...
2338    Tell your friends what you plan to do on Valen...
1899                      Wat would u like 4 ur birthday?
316                            K.k:)advance happy pongal.
1134    As I entered my cabin my PA said, '' Happy B'd...
Name: Message, Length: 1114, dtype: object

In [45]:
#transform the test data to feature vecors that can be used as input to Logistic Regression Model
feature_extraction = TfidfVectorizer(min_df = 1, stop_words='english', lowercase = True)

X_train_features = feature_extraction.fit_transform(X_train)
#dont use fit for the second one 
X_test_features = feature_extraction.transform(X_test)

#convert Y_train and Y_test values as integers
Y_train = Y_train.astype('int')
Y_test = Y_test.astype('int')

In [50]:
#modelling the Logistic Regression model
model = LogisticRegression().fit(X_train_features,Y_train)
model

LogisticRegression()

In [ ]:
#model evulation on train data
X_train_predict = model.predict(X_train_features)
predict_accuracy = accuracy_score(X_train_predict,Y_train)
print(predict_accuracy)

0.9066427289048474

In [ ]:
#model evulation on test data
X_test_predict = model.predict(X_test_features)
predict_accuracy_test = accuracy_score(X_test_predict,Y_test)
print(predict_accuracy_test)

0.9073575594436967